# Generated by Django 5.0.7 on 2024-08-21 03:57

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('message', models.TextField()),
                ('type', models.CharField(max_length=50)),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
