# Generated by Django 5.0.7 on 2024-08-21 03:57

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('hostname', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('serial_number', models.CharField(max_length=100, unique=True)),
                ('manufacturer', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
                ('os_type', models.CharField(max_length=50)),
                ('os_version', models.CharField(max_length=50)),
                ('cpu', models.CharField(max_length=100)),
                ('cpu_cores', models.IntegerField(default=2)),
                ('cpu_threads', models.IntegerField(default=1)),
                ('ram_total_gb', models.IntegerField(default=2)),
                ('disk_total_gb', models.IntegerField(default=128)),
                ('network_interfaces', models.JSONField(default=dict)),
                ('photo_url', models.URLField(blank=True, null=True)),
                ('status', models.CharField(choices=[('available', 'Available'), ('assigned', 'Assigned'), ('repair', 'In Repair')], default='available', max_length=50)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['date_added'],
            },
        ),
    ]
