# Generated by Django 5.0.7 on 2024-08-21 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('device', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='device',
            name='network_interfaces',
        ),
        migrations.AlterField(
            model_name='device',
            name='cpu',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='device',
            name='cpu_cores',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='device',
            name='cpu_threads',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='device',
            name='disk_total_gb',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='device',
            name='manufacturer',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='device',
            name='model',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='device',
            name='os_type',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='device',
            name='os_version',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='device',
            name='ram_total_gb',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='device',
            name='serial_number',
            field=models.CharField(max_length=250, unique=True),
        ),
    ]
